site_name: Ethicrawl
site_url: https://ethicrawl.github.io/ethicrawl/
repo_url: https://github.com/ethicrawl/ethicrawl
nav:
  - Home: index.md
  - Code Standards: standards.md
  - API Reference:
      - Overview: api/ethicrawl.md

theme: material
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
