site_name: Ethicrawl
site_url: https://ethicrawl.github.io/ethicrawl/
repo_url: https://github.com/ethicrawl/ethicrawl
nav:
  - Home: index.md
  - Code Standards: standards.md
  - API Reference:
      - Overview: api/overview.md
      - Ethicrawl: api/ethicrawl.md
      - Core: api/core.md
      - Context: api/context.md
      - Error Handling: api/error.md
      - Configuration: api/config.md
      - Logger: api/logger.md
      - Client: api/client.md
      - HttpClient: api/client.http.md
      - Robots: api/robots.md
      - Sitemaps: api/sitemaps.md

theme: material
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
