name: Security Scan

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit semgrep
          pip install -e .

      # Static code analysis with Bandit
      - name: Run Bandit
        run: bandit -r ethicrawl -f json -o bandit-results.json
        # Remove continue-on-error to make workflow fail on issues

      # Dependency vulnerability scanning with pip-audit
      # PYSEC-2022-43012: old version of setuptools on the runners, irrelevant
      - name: Run pip-audit
        run: pip-audit --ignore-vuln PYSEC-2022-43012 -f json -o pip-audit-results.json
        # Remove continue-on-error to make workflow fail on issues

      # Advanced code scanning with Semgrep
      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/python
          output: semgrep-results.json

      # Upload scan results as artifacts
      - name: Upload security scan results
        if: always() # always upload even on failure
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            bandit-results.json
            pip-audit-results.json
            semgrep-results.json
