name: security
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit black mypy pyright pip-audit semgrep
          pip install -e .

      # LINTING CHECKS
      - name: Run Black formatter check
        run: black --check .
        id: black

      - name: Run mypy type checking
        run: mypy ethicrawl
        id: mypy

      - name: Run pyright analysis
        run: pyright
        id: pyright

      # SECURITY CHECKS
      - name: Run Bandit
        run: bandit -r ethicrawl -f json -o bandit-results.json
        id: bandit

      - name: Run pip-audit
        run: pip-audit --ignore-vuln PYSEC-2022-43012 -f json -o pip-audit-results.json
        id: pip-audit

      - name: Run Semgrep
        run: semgrep scan --config=auto --json -o semgrep-results.json
        id: semgrep

      # Upload all results as artifacts
      - name: Upload scan results
        if: always() # always upload even on failure
        uses: actions/upload-artifact@v4
        with:
          name: security-and-lint-results
          path: |
            bandit-results.json
            pip-audit-results.json
            semgrep-results.json

      # Create summary report
      - name: Create job summary
        if: always()
        run: |
          echo "## Security and Linting Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Linting Checks" >> $GITHUB_STEP_SUMMARY
          echo "- Black: ${{ steps.black.outcome == 'success' && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Mypy: ${{ steps.mypy.outcome == 'success' && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Pyright: ${{ steps.pyright.outcome == 'success' && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY

          echo "### Security Checks" >> $GITHUB_STEP_SUMMARY
          echo "- Bandit: ${{ steps.bandit.outcome == 'success' && '✅ Passed' || '❌ Issues found' }}" >> $GITHUB_STEP_SUMMARY
          echo "- pip-audit: ${{ steps.pip-audit.outcome == 'success' && '✅ No vulnerabilities' || '⚠️ Vulnerabilities detected' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Semgrep: ${{ steps.semgrep.outcome == 'success' && '✅ Passed' || '❌ Issues found' }}" >> $GITHUB_STEP_SUMMARY