name: Security Scan

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit semgrep
          pip install -e .

      # Static code analysis with Bandit
      - name: Run Bandit
        run: bandit -r ethicrawl -f json -o bandit-results.json
        continue-on-error: true

      # Dependency vulnerability scanning with pip-audit
      - name: Run pip-audit
        run: pip-audit -o json -f pip-audit-results.json
        continue-on-error: true

      # Advanced code scanning with Semgrep
      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/python
          output: semgrep-results.json

      # Upload scan results as artifacts
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            bandit-results.json
            pip-audit-results.json
            semgrep-results.json
